### ISSUE TITLE
Fix docker ports

### ISSUE THREAD

**Issue by multiwebinc** [haiwen/seafile-admin-docs#117]
This is my first time ever using docker, so I could be totally wrong here on how it works, but it looks like there might be some places that it could be a bit clearer.

[https://manual.seafile.com/deploy/](https://manual.seafile.com/deploy/) says that:

> Since version 8.0, Docker is the recommended way [to deploy Seafile].

I therefore followed the [docker docs](https://manual.seafile.com/docker/deploy_seafile_with_docker/) and had a few hickups.

First, in the [docker-compose.yml file](https://download.seafile.com/d/320e8adf90fa43ad8fee/files/?p=/docker/docker-compose.yml)

```yaml
services:          
  seafile:
    ports:
      - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
```

First of all, shouldn't port 8082 be included as well? I can access port 8082 by going to the docker IP address, but not on `localhost:8082`.

Second, if proxying Seafile behind a web server, port 80 or 443 shouldn't be used since they will already be in use. Maybe do something like:

```yaml
services:          
  seafile:
    ports:
      - "80:80" # If deploying behind a web server, comment this line out.
#     - "8000:80"  # If deploying behind a web server, uncomment this line.
#     - "443:443"  # If https is enabled, uncomment this line.
      - "8082:8082"
```
