### ISSUE TITLE
Wrong elasticsearch volume seafile-server.yml 12 PE

### ISSUE THREAD

**Issue by Eidenz** [haiwen/seafile-admin-docs#412]
Hello, I am currently testing the upcoming seafile 12 version (on Pro Edition) and noticed a mistake in the provided docker compose file:
https://manual.seafile.com/12.0/docker/pro/seafile-server.yml

In the elastic search part:
```yaml
elasticsearch:
    image: ${SEAFILE_ELASTICSEARCH_IMAGE:-elasticsearch:8.15.0}
    container_name: seafile-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - "${SEAFILE_MYSQL_VOLUME:-/opt/seafile-elasticsearch/data}:/usr/share/elasticsearch/data"
    networks:
      - seafile-net
```

You are binding the MySQL volume instead of the correct `SEAFILE_ELASTICSEARCH_VOLUME`.
