### ISSUE TITLE
SeaSearch init env variables are wrongly defined

### ISSUE THREAD

**Issue by JavierAntonYuste** [haiwen/seafile-admin-docs#511]
For using SeaSearch, the following vars are specified in the manual:

```
...
INIT_SS_ADMIN_USER=<admin-username>  
INIT_SS_ADMIN_PASSWORD=<admin-password>
```

But in SeaSearch container, in `/opt/scripts/entrypoint.sh` the ZINC variables are exported differently:

```
  export ZINC_FIRST_ADMIN_USER=$SS_FIRST_ADMIN_USER
  export ZINC_FIRST_ADMIN_PASSWORD=$SS_FIRST_ADMIN_PASSWORD
```

Which makes SeaSearch unable to start the first time. Manual should be updated accordingly, either with the ones in the guide if that is the plan to use it in SeaSearch or if the SeaSearch scripts are done, update those in the guide.

 **Errors like this take ages to debug** so please take care with this kind of configs when developing.

**Comment by wacmkxiaoyi** [comment]
Hello JavierAntonYuste,

Very thanks for your post, but in our `seasearch.yml`, it should like that:

```yml
services:
  seasearch: 
    environment: 
      - SS_FIRST_ADMIN_USER=${INIT_SS_ADMIN_USER:-}
      - SS_FIRST_ADMIN_PASSWORD=${INIT_SS_ADMIN_PASSWORD:-}
```

Although the variable names in the script in the container (`SS_FIRST_xxx`) are inconsistent with the variable names passed in `.env` (`INIT_SS_`), the variables have been converted in `.yml`. Can you tell us in more detail why it failed to start for the first time? We have just tested and cannot reproduce the error you reported for the time being.

Good luck,
